name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - 'pypy-3.7'
          - 'pypy-3.8'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
      fail-fast: false
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Lint with pylint
        run: |
          pip install pylint
          # E1136 happens spuriously on Python 3.9 and pylint - https://github.com/PyCQA/pylint/issues/3882
          pylint --disable=C,R,W,E1136 apm
      - name: Run tests
        run: |
          python -m unittest -v
  rosetta:
    name: Run the comparison between apm and PEP-634 script on Python 3.10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - '3.10'
        os:
          - ubuntu-latest
          - macOS-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install apm
        run: |
          pip install .
      - name: Run Rosetta Script
        run: |
          python3 docs/pep634_vs_different_apm_styles.py
