name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
      fail-fast: false
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --disable=C,R,W apm
    - name: Run tests
      run: |
        python -m unittest -v
